### PR TITLE
changed demo to apply Template SED method

### PR DESCRIPTION
**Pull request by aimalz**
don't forget to put the .py file into the fastcat subdirectory and to change the directory where the .npy files are stored

### CODE REVIEW

**Comment by slosar** [comment]
Hi Alex,

This is fantastic progress, thanks a lot. But we need a couple more changes, before I merge this in.
In particular:
.) The thing works with pz_demo, but wouldn't work in general, I think because pzdemo simulates a single galaxy, while in general we have a full list of galaxies, stored in "arr". So, at the moment PofZ completely ignores arr, which means something is not quite right (it should return the vector of p(z)s for all object in arr).
.) You also need to implement other functions, like cumulative cPofZ, etc. Or at least make the code barf if it hits them. 
.) Also make sure all relevant information is stored in writeHDF5 so that we can recover it then.

Let me know if anything is confusing and then reissue the pull request. If you get stuck let me know and we can work it out together...

**Comment by aimalz** [comment]
Great, I'll modify the code to accommodate an array of redshifts, calculate cPofZ, and write output to HDF5.  Just so I can assign this task an appropriate priority relative to my other work, on what timescale do you expect to see these changes?

**Comment by slosar** [comment]
there is no rush, since we have plenty of other things to do (which we
can test using existing methods), but say 2-3 weeks would be great
otherwise we stall too much!

## 

anže

**Comment by aimalz** [comment]
Great, I can definitely do it by the end of the month and likely much sooner, just juggling a few too many projects right now.

**Comment by aimalz** [comment]
I just wanted to give you an update since it's been a couple weeks.  I implemented the changes you asked for but discovered a perplexing bug in the p(z) results themselves.  I'll submit another pull request when I figure out what's going wrong, but it's probably my own error using @ixkael's code.

**Comment by aimalz** [comment]
@ixkael found my bug, and everything works now.  I pushed some commits to my branch, so you should be able to merge the changes and approve the updated pull request, or I can submit a new one if you prefer.

I added a note to the demo, but just to be clear, the quality of the p(z) results depends strongly on the error model, which is currently hardcoded.  I can implement something more sophisticated if I can take error parameters as input along with the true redshifts.

**Comment by slosar** [comment]
Alex, ok, this looks pretty good, there are a couple small changes that could help, like loading in the constructor (all these self.f_type=np.load...) since some methods like pofz can be called many times and you don't wan to load every single time, etc. but all in all good. I'll pull over the weekend and let you know if there are any further issues.

**Comment by aimalz** [comment]
That's good to hear, thanks.  I think I could make it more efficient if I knew the relevant usage cases.  Perhaps you could add some to the demo?  I don't have the clearest idea of the big picture of what you're ultimately doing with this code.

**Pull request merged**
